[package]
name = "timetoreach"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtfs-structures = {path="gtfs-structure"}
rstar = "0.9.3"
proj = "0.27.0"
lazy_static = "1.4.0"
serde = {version = "1.0.148", features=["derive"]}
id-arena = "2.2.1"
bson = "2.4.0"
serde_json = "1.0.89"
bytemuck = {version ="1.12.3", features = ["extern_crate_alloc"]}
rmp-serde = "1.1.1"
rmp = "0.8.11"
serde_bytes = "0.11.7"
gdal = "0.14.0"

[workspace]
members = ["gtfs-structure"]

[profile.release]
debug=1