[package]
name = "timetoreach"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtfs-structures = {path="gtfs-structure"}
rstar = "0.9.3"
proj = "0.27.0"
lazy_static = "1.4.0"
serde = {version = "1.0.148", features=["derive"]}
id-arena = "2.2.1"
serde_json = "1.0.89"
gdal = {git="https://github.com/georust/gdal"}
geo-types = "0.7.8"
warp = "0.3.3"
tokio = {version="1.24.1", features=["full"]}
bson="2.4.0"

env_logger = "0.10.0"
[workspace]
members = ["gtfs-structure"]
