name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      DOCKER_WRITE: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_ACTIONS: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          tags: test:x86_64

