name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      DOCKER_WRITE: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_ACTIONS: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: rsync deployments
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr
          path: .
          remote_path: repo
          remote_host: 35.238.190.254
          remote_user: henry
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}